### ISSUE TITLE
Outstanding issues building using meson-python

### ISSUE THREAD

**Issue by ianthomas23** [contourpy/contourpy#224]
`meson-python` is now the build backend used after merging #183. There are a few outstanding issues/details to be resolved before an actual release of `contourpy` can be made using `meson-python`:

- [x] check appropriate debug/release build type and compiler flags e.g. optimisation level (fixed by #232)
- [x] check performance has not been affected (due to compiler flag changes above) (fixed by #232)
- [x] check can build all required wheels using `cibuildwheel`: (fixed by #249)
    - [X] macOS cross-compile needs a `meson-python` release containing mesonbuild/meson-python#406 (fixed by #231)
    - [x] win32 wheels (no longer releasing 32-bit, see #249)
- [x] storing build config settings so they are available at runtime, similar to `scipy` (fixed by #227)
- [x] decide on fate of `CONTOURPY_DEBUG` and similar (fixed by #227)
- [x] update developer's guide, including how to do editable installs, debug builds, change C++ standard, etc (fixed by #245)

(Edited to tick items when completed)
